name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        repository: danielga/garrysmod_common
        ref: master
        path: 'garrysmod_common'
    - name: Заинсталить всякую хуйню
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz -O premake.tar.gz
        tar -xvf premake.tar.gz
        chmod +x premake5
        sudo cp premake5 /usr/bin
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y liblz4-dev liblz4-dev:i386
        export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/lib:$LD_LIBRARY_PATH
        sudo apt-get -y --no-install-recommends install build-essential clang-9 cmake gdb git wget g++ g++-multilib gcc-multilib
        gcc --version
        git clone https://github.com/lz4/lz4.git $HOME/lz4
        cd $HOME/lz4 && make clean && make build && sudo make install && cd ../
    - name: Generate Project
      run: |
        premake5 --gmcommon=garrysmod_common gmake
    - name: Make
      run: |
        cd projects/linux/gmake
        make
        make config=release_x86
        ls
    - name: Upload Linux Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux_build_artifacts
        path: |
          projects/linux/gmake/**/x86/**
          projects/linux/gmake/**/x86_64/**
